String.prototype.contains=function(a){return-1<this.indexOf(a)};String.prototype.trim=function(a){var b=(this+"").replace(/(^[ \t\n\r\f\x0b\xa0]*)|([ \t\n\r\f\x0b\xa0]*$)/g,"");a&&(a=(a+"").replace(/([\[\]\(\)\.\?\/\*\{\}\+\$\^\:])/g,"\\$1"),b=b.replace(RegExp("(^["+a+"]*)|(["+a+"]*$)","g"),""));return b};String.prototype.hashCode=function(){for(var a=31,b=0,c=this.length;b<c;)a^=(a<<5)+(a>>2)+this.charCodeAt(b++);return a};
String.format=function(){for(var a=arguments[0],b=1;b<arguments.length;b++)a=a.replace(RegExp("\\{"+(b-1)+"\\}","ig"),arguments[b]);return a};Array.prototype.contains=function(a){if("string"==typeof a||"number"==typeof a)for(var b in this)if(a==this[b])return!0;return!1};String.prototype.evalScript=function(){var a="eval"+this.hashCode(),b=document.createElement("script");b.type="text/javascript";b.id=a;b.text=this;document.getElementsByTagName("head")[0].appendChild(b)};
var phpcom={isIE:navigator.userAgent.toLowerCase().contains("msie"),isIE6:navigator.userAgent.toLowerCase().contains("msie 6"),isGecko:navigator.userAgent.toLowerCase().contains("gecko"),isFirefox:navigator.userAgent.toLowerCase().contains("firefox")||this.isGecko,isSafari:navigator.userAgent.toLowerCase().contains("safari"),isOpera:navigator.userAgent.toLowerCase().contains("opera"),isWebKit:navigator.userAgent.toLowerCase().contains("webkit"),instdir:"",chanid:0,tid:0,path:"/",domain:document.domain,
prefix:"phpcom_",$:function(a){return!a?null:"object"==typeof a?a:document.getElementById(a)},setCookie:function(a,b,c){var d=new Date;if(""==b||0>c)b="",c=-2592E3;d.setTime(d.getTime()+1E3*c);document.cookie=escape(this.prefix+a)+"="+escape(b)+(d?"; expires="+d.toGMTString():"")+(this.path?"; path="+this.path:"/")+(this.domain?"; domain="+this.domain:"")},getCookie:function(a,b){a=this.prefix+a;var c=document.cookie.indexOf(a),d=document.cookie.indexOf(";",c);if(-1==c)return"";c=document.cookie.substring(c+
a.length+1,d>c?d:document.cookie.length);return!b?unescape(c):c},delCookie:function(a){a=this.prefix+a;var b=new Date;b.setTime(b.getTime()-1);document.cookie=a+"=; expires="+b.toGMTString()+(this.path?"; path="+this.path:"/")+(this.domain?"; domain="+this.domain:"")},addEvent:function(a,b,c,d){a=!d?a:d;a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)},delEvent:function(a,b,c,d){a=!d?a:d;a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+
b,c)},endEvent:function(a){(a=a?a:window.event)||(a=getEvent());if(!a)return null;a.preventDefault?a.preventDefault():a.returnValue=!1;a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;return a}};function $(a){return!a?null:"object"==typeof a?a:document.getElementById(a)}function $T(a){return"string"==typeof a?document.getElementsByTagName(a):null}function display(a){$(a).style.display=""==$(a).style.display?"none":""}function isUndefined(a){return"undefined"==typeof a||null==a?!0:!1}
function undef(a,b){return"undefined"==typeof a||null==a?b:a}function preg_replace(a,b,c,d){d=!d?"ig":d;for(var e=a.length,g=0;g<e;g++)re=RegExp(a[g],d),c=c.replace(re,"string"==typeof b?b:b[g]?b[g]:b[0]);return c}function htmlspecialchars(a){return preg_replace(["&","<",">",'"'],["&amp;","&lt;","&gt;","&quot;"],a)}function strlen(a){return phpcom.isIE&&-1!=a.indexOf("\n")?a.replace(/\r?\n/g,"_").length:a.length}
function empty(a){if(""===a||0===a||"0"===a||null===a||!1===a||"undefined"===typeof a)return!0;if("object"==typeof a){for(var b in a)return!1;return!0}return!1}function str_repeat(a,b){for(var c=[];0<b;c[--b]=a);return c.join("")}
function sprintf(){for(var a=0,b,c=arguments[a++],d=[],e,g,f;c;){if(e=/^[^\x25]+/.exec(c))d.push(e[0]);else if(e=/^\x25{2}/.exec(c))d.push("%");else if(e=/^\x25(?:(\d+)\$)?(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-fosuxX])/.exec(c)){if(null==(b=arguments[e[1]||a++])||void 0==b)throw"Too few arguments.";if(/[^s]/.test(e[7])&&"number"!=typeof b)throw"Expecting number but found "+typeof b;switch(e[7]){case "b":b=b.toString(2);break;case "c":b=String.fromCharCode(b);break;case "d":b=parseInt(b);break;
case "e":b=e[6]?b.toExponential(e[6]):b.toExponential();break;case "f":b=e[6]?parseFloat(b).toFixed(e[6]):parseFloat(b);break;case "o":b=b.toString(8);break;case "s":b=(b=String(b))&&e[6]?b.substring(0,e[6]):b;break;case "u":b=Math.abs(b);break;case "x":b=b.toString(16);break;case "X":b=b.toString(16).toUpperCase()}b=/[def]/.test(e[7])&&e[2]&&0<=b?"+"+b:b;g=e[3]?"0"==e[3]?"0":e[3].charAt(1):" ";f=e[5]-String(b).length-0;g=e[5]?str_repeat(g,f):"";d.push(""+(e[4]?b+g:g+b))}else throw"Huh ?!";c=c.substring(e[0].length)}return d.join("")}
function getEvent(){if(document.all)return window.event;for(func=getEvent.caller;null!=func;){var a=func.arguments[0];if(a&&(a.constructor==Event||a.constructor==MouseEvent||"object"==typeof a&&a.preventDefault&&a.stopPropagation))return a;func=func.caller}return null}var evalscripts=[];
function parsescript(a){return-1==a.indexOf("<script")?a:a=a.replace(/<script(.*?)>([^\x00]*?)<\/script>/ig,function(a,c,d){a=charset="";var e=!1;c.match(/\s*src\s*=\"([^\"]+?)\"/i)&&(a=RegExp.$1,d="");c.match(/\s*charset\s*=\"([^\"]+?)\"/i)&&(charset=RegExp.$1);e=-1!=c.indexOf("reload=");appendscript(a,d,e,charset);return""})}
function appendscript(a,b,c,d){var e="Ajax"+(a+b).hashCode();if(c||!evalscripts.contains(e)){c&&$(e)&&$(e).parentNode.removeChild($(e));evalscripts.push(e);var g=document.createElement("script");g.type="text/javascript";g.id=e;try{a?(g.src=a,d&&(g.charset=d),g.onloadDone=!1,g.onload=function(){g.onloadDone=!0},g.onreadystatechange=function(){if(("loaded"==g.readyState||"complete"==g.readyState)&&!g.onloadDone)g.onloadDone=!0}):b&&(g.text=b),document.getElementsByTagName("head")[0].appendChild(g)}catch(f){}return!0}}
var loadRecord={};function loadscript(a,b){if("undefined"==typeof loadRecord[a]){var c=document.createElement("script");c.type="text/javascript";try{c.src=a,b&&(c.charset=b),c.onloadDone=!1,c.onload=function(){c.onloadDone=!0},c.onreadystatechange=function(){if(("loaded"==c.readyState||"complete"==c.readyState)&&!c.onloadDone)c.onloadDone=!0},document.getElementsByTagName("head")[0].appendChild(c),loadRecord[a]=!0}catch(d){}return!0}}
function loadcss(a){if("undefined"==typeof loadRecord[a]){var b=document.createElement("link");b.rel="stylesheet";b.type="text/css";try{b.href=a,document.getElementsByTagName("head")[0].appendChild(b),loadRecord[a]=!0}catch(c){}return!0}}
function ajaxObject(a){var b={createXMLHttpRequest:function(){var a=!1;if(window.XMLHttpRequest)a=new XMLHttpRequest,a.overrideMimeType&&a.overrideMimeType("text/xml");else if(window.ActiveXObject)for(var b="Microsoft.XMLHTTP MSXML.XMLHTTP Microsoft.XMLHTTP Msxml2.XMLHTTP.7.0 Msxml2.XMLHTTP.6.0 Msxml2.XMLHTTP.5.0 Msxml2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP".split(" "),e=0;e<b.length;e++)try{if(a=new ActiveXObject(b[e]))return a}catch(g){}return a}};b.xmlhttp=b.createXMLHttpRequest();b.responseText=
"";b.url="";b.waitid=null;b.recallback=null;b.recvType=a?a:"XML";b.setRecvType=function(a){b.recvType=a};b.setWaiting=function(a){b.waitid=$(a)};b.post=function(a,d,e){b.url=a;setTimeout(function(){b.loading()},200);b.xmlhttp.onreadystatechange=b.onreadyStateHandle;b.recallback=e;b.xmlhttp.open("POST",a);b.xmlhttp.setRequestHeader("Content-Type","application/x-www-form-urlencoded");b.xmlhttp.setRequestHeader("X-Requested-With","XMLHttpRequest");b.xmlhttp.send(d)};b.get=function(a,d){b.url=a;setTimeout(function(){b.loading()},
200);b.xmlhttp.onreadystatechange=b.onreadyStateHandle;b.recallback=d;window.XMLHttpRequest?setTimeout(function(){b.xmlhttp.open("GET",a);b.xmlhttp.setRequestHeader("X-Requested-With","XMLHttpRequest");b.xmlhttp.send(null)},500):setTimeout(function(){b.xmlhttp.open("GET",a,!0);b.xmlhttp.setRequestHeader("X-Requested-With","XMLHttpRequest");b.xmlhttp.send()},500)};b.onreadyStateHandle=function(){if(4==b.xmlhttp.readyState&&200==b.xmlhttp.status){if("HTML"==b.recvType)b.responseText=b.xmlhttp.responseText;
else if("XML"==b.recvType)if(!b.xmlhttp.responseXML||!b.xmlhttp.responseXML.lastChild||"parsererror"==b.xmlhttp.responseXML.lastChild.localName)try{b.responseText=b.xmlhttp.responseText;var a=/<!\[CDATA\[([\s\S]+)\]\]>/.exec(b.responseText);a&&a[1]&&(b.responseText=a[1].replace(/^\s+|\s+$/g,""))}catch(d){b.responseText='<a href="'+b.url+'" target="_blank" style="color:red">\u53d1\u751f\u5185\u90e8\u9519\u8bef\uff0c\u65e0\u6cd5\u663e\u793a\u5185\u5bb9</a>'}else b.responseText=b.xmlhttp.responseXML.lastChild.firstChild.nodeValue;
b.waitId&&(b.waitId.style.display="none");"function"==typeof b.recallback&&b.recallback(b.responseText);delete b.xmlhttp}};b.loading=function(){if(b.waitId&&(4!=b.xmlhttp.readyState||200!=b.xmlhttp.status))b.waitid.style.display="",b.waitid.innerHTML='<span class="loading-16"></span>'};return b}
function phpcomMenu(){this.active=[];this.timeouts=[];this.dragOffset=[];this.layer=0;this.zindex={window:1E4,menu:2E4,dialog:3E4,message:4E4};this.ie=phpcom.isIE;this.ie6=phpcom.isIE6;this.firefox=phpcom.isFirefox;this.opera=phpcom.isOpera;this.safari=phpcom.isSafari}
phpcomMenu.prototype={show:function(a){var b=menu,c=isUndefined(a.ctrlid)?"object"==typeof a?null:a:a.ctrlid,d=isUndefined(a.showid)?c:a.showid,e=isUndefined(a.menuid)?d+"_menu":a.menuid,g=$(c),f=$(e);if(f){var k=isUndefined(a.type)?"menu":a.type,m=isUndefined(a.event)?"mouseover":a.event,l=isUndefined(a.pos)?"43":a.pos,h=isUndefined(a.layer)?1:a.layer,j=isUndefined(a.maxh)?600:a.maxh,n=isUndefined(a.duration)?2:a.duration,r=isUndefined(a.timeout)?500:a.timeout,q=isUndefined(a.cache)?1:a.cache,p=
isUndefined(a.drag)?"":a.drag,t=p&&$(p)?$(p):f,u=isUndefined(a.fade)?0:a.fade,s=isUndefined(a.mask)?0:a.mask;a=isUndefined(a.zindex)?this.zindex.menu:a.zindex;a=s?a+3E4:a;"undefined"==typeof b.active[h]&&(b.active[h]=[]);if("click"==m&&b.active[h].contains(e)&&"win"!=k)b.hide(e,k);else{"menu"==k&&this.hide(h,k);g&&!g.getAttribute("initialized")&&(g.setAttribute("initialized",!0),g.unselectable=!0,g.outfunc="function"==typeof g.onmouseout?g.onmouseout:null,g.onmouseout=function(){this.outfunc&&this.outfunc();
3>n&&!b.timeouts[e]&&(b.timeouts[e]=setTimeout("menu.hide('"+e+"', '"+k+"')",r))},g.overfunc="function"==typeof g.onmouseover?g.onmouseover:null,g.onmouseover=function(a){b.cancel(a);this.overfunc&&this.overfunc();if("click"==m)clearTimeout(b.timeouts[e]),b.timeouts[e]=null;else for(var c in b.timeouts)b.timeouts[c]&&(clearTimeout(b.timeouts[c]),b.timeouts[c]=null)});if(!f.getAttribute("initialized")&&(f.setAttribute("initialized",!0),f.ctrlkey=c,f.mtype=k,f.layer=h,f.mask=s,f.style.position="absolute",
f.style.zIndex=a+h,f.style.direction="ltr",f.onclick=function(a){if(!a||b.ie)return window.event.cancelBubble=!0,window.event;a.stopPropagation();return a},3>n&&(1<n&&(f.onmouseover=function(){clearTimeout(b.timeouts[e]);b.timeouts[e]=null}),1!=n&&(f.onmouseout=function(){b.timeouts[e]=setTimeout("menu.hide('"+e+"', '"+k+"')",r)})),s)){c=document.documentElement&&document.documentElement.clientHeight||document.body.clientHeight;g=document.documentElement.scrollWidth;if(a=$(e+"_mask"))a.style.display=
"";else{a=document.createElement("div");try{document.body.insertBefore(a,null)}catch(v){}}a.id=e+"_mask";a.className="flmask";a.style.position=b.ie6?"absolute":"fixed";a.style.zIndex=f.style.zIndex-1;a.style.left=a.style.top="0px";a.style.width="100%";a.style.height=(g>c?g:c)+"px";a.style.backgroundColor="#fff";a.style.filter="progid:DXImageTransform.Microsoft.Alpha(opacity=55)";a.style.opacity=0.55}p&&(t.style.cursor="move",t.onmousedown=function(a){try{b.dragMenu(f,a,1)}catch(c){}});f.style.display=
"";s&&($(e+"_mask").style.display="");if(u){var w=function(a){if(100==a)clearTimeout(b);else{f.style.filter="progid:DXImageTransform.Microsoft.Alpha(opacity="+a+")";f.style.opacity=a/100;a+=10;var b=setTimeout(function(){w(a)},50)}};w(0);f.fade=!0}else f.fade=!1;"*"!=l&&this.setPosition(d,e,l);j&&f.scrollHeight>j&&(f.style.height=j+"px",b.opera?f.style.overflow="auto":f.style.overflowY="auto");n||setTimeout("menu.hide('"+e+"', '"+k+"')",r);if("menu"!=k&&b.ie6&&"IFRAME"==f.lastChild.tagName){b.ie6Mask(f);
d=f.getElementsByTagName("*");l=!1;for(j=0;j<d.length;j++)if(d[j].autoresize){l=parseInt(d[j].autoresize);break}l&&phpcom.addEvent(f,"click",function(){b.ie6Mask(f)})}b.active[h].contains(e)||b.active[h].push(e);f.cache=q;h>b.layer&&(b.layer=h)}}},ie6Mask:function(a){var b=a.firstChild;a.lastChild.style.height=b.offsetHeight+"px";a.lastChild.style.width=b.offsetWidth+"px"},dragMenu:function(a,b,c){var d=menu;b=b?b:window.event;if(1==c){if(!["TEXTAREA","INPUT","BUTTON","SELECT"].contains(d.ie?b.srcElement.tagName:
b.target.tagName))d.dragOffset=[b.clientX,b.clientY],d.dragOffset[2]=parseInt(a.style.left),d.dragOffset[3]=parseInt(a.style.top),document.onmousemove=function(b){try{d.dragMenu(a,b,2)}catch(c){}},document.onmouseup=function(b){try{d.dragMenu(a,b,3)}catch(c){}},d.cancel(b)}else 2==c&&d.dragOffset[0]?(c=[b.clientX,b.clientY],a.style.left=d.dragOffset[2]+c[0]-d.dragOffset[0]+"px",a.style.top=d.dragOffset[3]+c[1]-d.dragOffset[1]+"px",d.cancel(b)):3==c&&(d.dragOffset=[],document.onmousemove=null,document.onmouseup=
null)},hide:function(a,b){var c=menu;a=isUndefined(a)?"":a;b=isUndefined(b)?"menu":b;if(""==a)for(var d=1;d<=c.layer;d++)this.hide(d,b);else if("number"==typeof a)for(d in c.active[a])this.hide(c.active[a][d],b);else if("string"==typeof a){var e=$(a);if(e&&!(b&&e.mtype!=b)){clearTimeout(c.timeouts[a]);var g=function(){e.cache?(e.style.display="none",e.mask&&($(a+"_mask").style.display="none")):(e.parentNode.removeChild(e),e.mask&&$(a+"_mask").parentNode.removeChild($(a+"_mask")));var b=[],d;for(d in c.active[e.layer])a!=
c.active[e.layer][d]&&b.push(c.active[e.layer][d]);c.active[e.layer]=b};if(e.fade){var f=function(a){if(0==a)clearTimeout(b),g();else{e.style.filter="progid:DXImageTransform.Microsoft.Alpha(opacity="+a+")";e.style.opacity=a/100;a-=10;var b=setTimeout(function(){f(a)},50)}};f(100)}else g()}}},cancel:function(a){(a=a?a:window.event)||(a=getEvent());if(!a)return null;a.preventDefault?a.preventDefault():a.returnValue=!1;a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;return a},setPosition:function(a,
b,c){var d=menu,e=$(a);a=b?$(b):$(a+"o");isUndefined(c)&&(c="43");b=parseInt(c.substr(0,1));var g=parseInt(c.substr(1,1)),f=0,k=0,m=f=0,l=0,h=0,j=0,n=0,r=0,q=0,p=0;if(a&&(!(0<b)||e)){e&&(f=this.offsetPos(e),k=f.x,f=f.y,m=e.offsetWidth,l=e.offsetHeight);var n=a.offsetWidth,r=a.offsetHeight,t=document.documentElement&&document.documentElement.clientWidth||document.body.clientWidth,u=document.documentElement&&document.documentElement.clientHeight||document.body.clientHeight;switch(b){case 1:q=k;p=f;
break;case 2:q=k+m;p=f;break;case 3:q=k+m;p=f+l;break;case 4:q=k,p=f+l}switch(g){case 0:a.style.left=(t-a.clientWidth)/2+"px";j=(u-a.clientHeight)/2;break;case 1:h=q-n;j=p-r;break;case 2:h=q;j=p-r;break;case 3:h=q;j=p;break;case 4:h=q-n,j=p}var s=Math.max(document.documentElement.scrollTop,document.body.scrollTop),v=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);[1,4].contains(g)&&0>h?(h=q,[1,4].contains(b)&&(h+=m)):h+n>v+t&&k>=n&&(h=q-n,[2,3].contains(b)&&(h-=m));[1,2].contains(g)&&
0>j?(j=p,[1,2].contains(b)&&(j+=l)):j+r>s+u&&f>=r&&(j=p-r,[3,4].contains(b)&&(j-=l));"210"==c&&(h+=69-m/2,j-=5,"TEXTAREA"==e.tagName&&(h-=m/2,j+=l/2));if(0==g||a.scrolly)d.ie6?0==g&&(j+=s):(a.scrolly&&(j-=s),a.style.position="fixed");h&&(a.style.left=h+"px");j&&(a.style.top=j+"px");0==g&&(d.ie&&!document.documentElement.clientHeight)&&(a.style.position="absolute",a.style.top=(document.body.clientHeight-a.clientHeight)/2+"px");a.style.clip&&!d.opera&&(a.style.clip="rect(auto, auto, auto, auto)")}},
offsetPos:function(a){var b=0,c=0;if(a.getBoundingClientRect){a=a.getBoundingClientRect();var c=Math.max(document.documentElement.scrollTop,document.body.scrollTop),b=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),d=document.documentElement&&document.documentElement.clientWidth||document.body.clientWidth;"rtl"==document.documentElement.dir&&(b=b+d-d);b=a.left+b-document.documentElement.clientLeft;c=a.top+c-document.documentElement.clientTop}return{x:b,y:c}},initTable:function(a,
b,c,d,e,g,f){d=d?d:"dialog";e=e?e:"fdrag_ctrl";g=g?g:"fbox_message_close";events=' style="cursor:move" onmousedown="menu.dragMenu($(\''+b+"'), event, 1)\"";f='<table id="'+b+'_table" cellpadding="0" cellspacing="0" class="fltable"><tr><td class="ftl"></td><td class="ftc"'+events+'></td><td class="ftr"></td></tr><tr><td class="fml"'+events+"></td><td"+(f?' id="'+f+'"':"")+' class="flbody">';isUndefined(c)||(f=f+('<ul class="flh" id="'+e+'" style="cursor:move;"><li class="x">'+c+"</li>")+('<li class="y"><a class="fclose" id="'+
g+'" onclick="menu.hide(\''+b+"','"+d+'\')" href="javascript:;" onmousedown="return false;">x</a></li></ul>'));f+=a;f+='<div style="clear:both;"></div></td><td class="fmr"'+events+'></td></tr><tr><td class="fbl"></td><td class="fbc"'+events+'></td><td class="fbr"></td></tr></table>';this.ie6&&(f+='<iframe id="'+b+'_iframe" frameborder="0" style="position:absolute;left:0;top:0;border:none;background-color:#ff0;opacity:0;filter:alpha(opacity=0);z-index:-1;display:block;"></iframe>');return f}};
var menu=new phpcomMenu;function showMenu(a){menu.show(a)}function hideMenu(a,b){menu.hide(a,b)}function hideDialog(a){menu.hide(a,"dialog")}function hideWindow(a,b,c){b=isUndefined(b)?1:b;a="fbox_"+a;c=isUndefined(c)?1:c;menu.hide(a,"window");c&&$(a)&&document.body.removeChild($(a));b&&hideMenu()}
function checkall(a,b,c){b=b?b:"chkall";for(var d=0,e=0;e<a.elements.length;e++){var g=a.elements[e];if(g.name&&g.name!=b&&(!c||c&&g.name.match(c)))g.checked=a.elements[b].checked,g.checked&&d++}return d}function check_all(a){"object"!=typeof a&&(a=document.forms[0]);for(var b=null,c=0;c<a.elements.length-1;c++){var d=a.elements[c];if("checkbox"==d.type&&(null===b&&(b=!d.checked),d.checked=b,"function"==typeof d.onclick))d.onclick()}return b}
function formatsize(a){for(var b=0;1024<a;)b++,a/=1024;a=parseFloat(a).toFixed(2);return a+["B","KB","MB","GB","TB"][b]}function doCopyEx(a){a=$(a);var b=a.value,b=null==b||""==b?a.innerHTML:b;if(phpcom.isIE)window.clipboardData.clearData(),clipboardData.setData("Text",b);else return setClipboard(b)}function runCodeEx(a){var b=$(a);a=b.value;if(a=null==a||""==a?b.innerHTML:a)b=window.open("","",""),b.opener=null,b.document.write(a),b.document.close()}
function saveAsCodeEx(a){var b=$(a);a=b.value;a=null==a||""==a?b.innerHTML:a;b=window.open("","_blank","top=1000");b.document.open("text/html","replace");b.document.charset="GB2312";b.document.write(a);b.document.execCommand("saveas",!1,"code.htm");b.close()}
function copyBlockCode(a){a=$(a);if(phpcom.isIE)a=a.innerText.replace(/\r\n\r\n/g,"\r\n");else{a=a.getElementsByTagName("li");for(var b=[],c=0,d=a.length;c<d;c++)b.push(a[c].textContent.replace(/\\x/g,"\\X"));a=b.join("\r\n")}a=a.replace(/[\xA0]/g," ");return setClipboard(a)}
function setClipboard(a,b){if(window.clipboardData)window.clipboardData.setData("Text",a);else{b=isUndefined(b)?"/":b;var c=function(){window.clip=new ZeroClipboard.Client;clip.setHandCursor(!0);clip.addEventListener("complete",function(){setTimeout(hideMenu("message_dialog","dialog"),500)});clip.setText(a);showMessage('<div id="clipboard_container" class="clipboard" style="position:relative;margin:auto;"><div id="clipboard_button" style="text-align:center;cursor:pointer;">\u70b9\u8fd9\u91cc\u590d\u5236\u5230\u526a\u8d34\u677f</div></div>',
"\u590d\u5236\u4ee3\u7801","cancel");clip.glue("clipboard_button","clipboard_container")};if(window.clip)c();else{var d=document.createElement("script");d.src=b+"misc/js/ZeroClipboard.js";d.onloadDone=!1;d.onload=function(){d.onloadDone=!0;ZeroClipboard.setMoviePath(b+"misc/js/ZeroClipboard.swf");c()};d.onreadystatechange=function(){if(("loaded"==d.readyState||"complete"==d.readyState)&&!d.onloadDone)d.onloadDone=!0,ZeroClipboard.setMoviePath(b+"misc/js/ZeroClipboard.swf"),c()};document.body.appendChild(d)}}return!1}
function thumbimg(){}function zoomimg(){}
function showMessage(a,b,c,d,e){c=isUndefined(c)?"alert":c;b=isUndefined(b)?"\u8b66\u544a\u4fe1\u606f":b;a=isUndefined(a)?"\u51fa\u9519\u5566!":a;var g=1,f="",k=$("fbox_message");k&&hideDialog("fbox_message");k=document.createElement("div");k.style.display="none";k.id="fbox_message";k.className="fwrap";try{document.body.insertBefore(k,null)}catch(m){}a=a.replace(/<script[^\>]*?>([^\x00]*?)<\/script>/ig,"");var l='<div class="fmessage">';"success"==c||"succeed"==c?(g=0,l+='<table><tr><td><span class="success-icons">&nbsp;</span></td><td>'+
a+"</td></tr></table>"):"error"==c?l+='<table><tr><td><span class="error-icons">&nbsp;</span></td><td>'+a+"</td></tr></table>":"info"==c?l+='<table><tr><td><span class="info-icons">&nbsp;</span></td><td>'+a+"</td></tr></table>":"alert"==c||"confirm"==c?l+='<table><tr><td><span class="alert-icons">&nbsp;</span></td><td>'+a+"</td></tr></table>":(g=0,l+=a);l+="</div>";"none"!=c&&(l=l+("cancel"!=c?'<div class="fbutton"><button id="dialog_submit_button" title="\u786e\u5b9a">&nbsp;\u786e\u5b9a&nbsp;</button>':
'<div class="fbutton">')+("confirm"==c||"cancel"==c?'<button id="dialog_cancel_button" title="\u53d6\u6d88">&nbsp;\u53d6\u6d88&nbsp;</button></div>':"</div>"));l+='<div class="fbottom"></div>';phpcom.isIE||(f='<style type="text/css">object{visibility:hidden;}</style>');a=menu.initTable(l,"fbox_message",b,"dialog",null,null,"mcontent");k.innerHTML=f+a;$("dialog_submit_button")&&($("dialog_submit_button").onclick=function(){"function"==typeof d?d():eval(d);hideDialog("fbox_message")},$("dialog_cancel_button")||
($("fbox_message_close")&&($("fbox_message_close").onclick=$("dialog_submit_button").onclick),$("fdrag_ctrl")&&($("fdrag_ctrl").ondblclick=$("dialog_submit_button").onclick)));$("dialog_cancel_button")&&($("dialog_cancel_button").onclick=function(){"function"==typeof e?e():eval(e);hideDialog("fbox_message")},$("fbox_message_close")&&($("fbox_message_close").onclick=$("dialog_cancel_button").onclick),$("fdrag_ctrl")&&($("fdrag_ctrl").ondblclick=$("dialog_cancel_button").onclick));menu.show({cache:0,
menuid:"fbox_message",type:"dialog",pos:"00",zindex:menu.zindex.message,duration:3,drag:"fdrag_ctrl",mask:g});try{$("dialog_submit_button")&&$("dialog_submit_button").focus()}catch(h){}return!1}
function showDialog(a,b,c){c=isUndefined(c)?!1:c;var d=$("fbox_dialog");d&&menu.hide("fbox_dialog","dialog");d=document.createElement("div");d.style.display="none";d.id="fbox_dialog";d.className="fwrap";try{document.body.insertBefore(d,null)}catch(e){}a=menu.initTable(a,"fbox_dialog",b,"dialog","fbox_dialog_drag","fbox_dialog_close");d.innerHTML=a;menu.show({cache:0,menuid:"fbox_dialog",type:"dialog",pos:"00",zindex:menu.zindex.dialog,duration:3,drag:"show_dialog_drag",mask:c});return!1}
function openDialog(a,b,c,d,e,g,f){b=isUndefined(b)?"frmae":b;c=isUndefined(c)?"":c;g=isUndefined(g)?0:g;f=isUndefined(f)?0:f;f="fbox_dialog_"+b;var k="dialog_ifrmae_"+b;d=isUndefined(d)?300:d;e=isUndefined(e)?200:e;var m=$(f);m&&menu.hide(f,"dialog");m=document.createElement("div");m.style.display="none";m.id=f;m.className="fwrap";try{document.body.insertBefore(m,null)}catch(l){}c=menu.initTable('<div id="dialog_frame_loader" style="width:'+d+"px;height:"+e+'px;"><div class="loading"></div></div><iframe style="display:none;overflow-x:hidden;" id="'+
k+'" name="'+k+'" src="about:blank" width="'+d+'" height="'+e+'" frameborder="0" scrolling="auto" allowtransparency="yes"></iframe>',f,c,"dialog","fbox_drag_"+b,"fbox_close_"+b);m.innerHTML=c;var h=$(k);h.src=a;phpcom.addEvent(h,"load",function(){$("dialog_frame_loader").style.display="none";h.style.display=""});menu.show({cache:0,menuid:f,type:"dialog",pos:"00",zindex:menu.zindex.dialog,duration:3,drag:"dialog_drag_"+b,mask:g});return!1}
function showWindow(a,b,c,d,e){c=isUndefined(c)?"get":c;d=isUndefined(d)?1:d;b=isUndefined(b)?c:b;e=isUndefined(e)?0:e;var g="fbox_"+b,f=$(g),k="ajax_content_"+b,m=null,l=null,h=function(){"get"==c?(f.url=a,a+=(0<a.search(/\?/)?"&":"?")+"winkey="+b,ajaxget(a,k,null,function(a){j();n(a)})):"post"==c&&(f.act=$(a).action,ajaxpost(a,k,null,function(a){j();n(a)}));phpcom.isIE6||(l=setTimeout(function(){showDialog('<div class="loading-ajax"></div>')},100))},j=function(){clearTimeout(l);$("fdrag_"+b)&&(m=
"fdrag_"+b);for(var a=f.getElementsByTagName("*"),c=0;c<a.length;c++)if("fld"==a[c].className){a[c].id||(a[c].id="fdrag_"+b);m=a[c].id;break}},n=function(a){hideMenu("fbox_dialog","dialog");if(""==a)return hideWindow(b,"window");menu.show({cache:d,menuid:g,type:"window",pos:"00",zindex:menu.zindex.window,duration:3,drag:null==typeof m?"":m,mask:e})};if(f)"get"==c&&(a!=f.url||1!=d)||"post"==c&&$(a).action!=f.act?h():n();else{f=document.createElement("div");f.style.display="none";f.id=g;f.className=
"fwrap";try{document.body.insertBefore(f,null)}catch(r){}var q=menu.initTable('<div class="loading-ajax"></div>',g,null,"window",null,null,k);f.innerHTML=q;"html"==c?($(k).innerHTML=a,j(),n()):h()}phpcom.endEvent()}
function ajaxpost(a,b,c,d){c=$(c);var e=$("ajaxpostframe");$(a);var g=function(){var a="";try{a=$("ajaxpostframe").contentWindow.document.XMLDocument.text}catch(f){try{a=$("ajaxpostframe").contentWindow.document.documentElement.firstChild.wholeText;if("undefined"==typeof a){var h=$("ajaxpostframe").contentDocument.documentElement;h.firstChild&&h.removeChild(h.firstChild);a=h.textContent}if("undefined"==typeof a){var a=$("ajaxpostframe").contentWindow.document.documentElement.innerText,j=/<!\[CDATA\[([\s\S]+)\]\]>/.exec(a);
j&&j[1]&&(a=j[1].replace(/^\s+|\s+$/g,""))}}catch(k){try{a=$("ajaxpostframe").contentWindow.document.documentElement.firstChild.nodeValue}catch(r){a="\u5185\u90e8\u9519\u8bef\uff0c\u65e0\u6cd5\u663e\u793a\u6b64\u5185\u5bb9"}}}c&&(c.disabled=!1);""!=a&&(a=parsescript(a));a&&b&&("onerror"==b?(a=msg.replace(/<script[^\>]*?>([^\x00]*?)<\/script>/ig,""),""!==a&&showMessage(a,"\u9519\u8bef\u4fe1\u606f","alert")):"onerror"!=b&&$(b)&&($(b).innerHTML=a));"function"==typeof d?d(a):d&&eval(d);e.loading=0;phpcom.delEvent(e,
"load",g);setTimeout(function(){document.body.removeChild(e.parentNode)},200)};if(e){if(e.loading)return!1}else{var f=document.createElement("div");f.style.display="none";f.innerHTML='<iframe src="about:blank" name="ajaxpostframe" id="ajaxpostframe" loading="1"></iframe>';try{document.body.insertBefore(f,document.body.firstChild)}catch(k){}e=$("ajaxpostframe")}f=$(a).getAttribute("action").replace(/\&inajax\=1/g,"");$(a).setAttribute("action",f+(0<=f.indexOf("?")?"&inajax=1":"?inajax=1"));$(a).target=
"ajaxpostframe";$(a).submit();phpcom.addEvent(e,"load",g);c&&(c.disabled=!0);phpcom.endEvent();return!1}function ajaxget(a,b,c,d){c=ajaxObject();var e=(new Date).getTime();a+=0<=a.indexOf("?")?"&t="+e:"?t="+e;a=a.replace(/\&inajax\=1/g,"")+"&inajax=1";c.get(a,function(a){var c="";!isUndefined(b)&&$(b)?(c=parsescript(a),""!=c&&($(b).innerHTML=c,$(b).style.display="")):""!=a&&(c=parsescript(a));!isUndefined(d)&&"function"==typeof d?d(c):isUndefined(d)||eval(d)});return!1}
function ctrlEnter(a,b,c){isUndefined(c)&&(c=0);return(a.ctrlKey||c)&&13==a.keyCode?($(b).click(),!1):!0}function checkUserInput(a){-1!=a.className.indexOf("gray")?(a.value="",a.className=a.className.replace("gray","black")):""==a.value&&(a.value=a.defaultValue="\u8bf7\u8f93\u7528\u6237\u540d",a.className=-1==a.className.indexOf("black")?a.className+" gray":a.className.replace("black","gray"))}
function checkSearchFocus(a){a=$(a);"\u8bf7\u8f93\u5165\u641c\u7d22\u5173\u952e\u5b57"==a.value&&(a.value="")}function checkSearchInput(a){""==a.value?a.value="\u8bf7\u8f93\u5165\u641c\u7d22\u5173\u952e\u5b57":"\u8bf7\u8f93\u5165\u641c\u7d22\u5173\u952e\u5b57"==a.value&&(a.value="")}function updateCaptcha(a,b){b||(b="");a.src=b+"apps/misc.php?action=captcha&t="+(new Date).getTime()}
function checkCaptcha(a,b,c){var d=$(a).value.trim();b||(b="");c||(c="checkCaptcha");if(""!=d){var e=$(c);e.style.display="";var g=e.getElementsByTagName("IMG")[0];4!=d.length?g?g.src=b+"misc/images/common/chkerr.gif":e.className="chkerr":(c=b+"apps/misc.php?action=captcha&inajax=1&token=captcha&check=yes&verifycode="+(phpcom.isIE&&"utf-8"==document.charset?encodeURIComponent(d):d),d=ajaxObject(),d.setWaiting(a),d.get(c,function(a){"succeed"==a.substr(0,7)?g?g.src=b+"misc/images/common/chksuc.gif":
e.className="chksuc":g?g.src=b+"misc/images/common/chkerr.gif":e.className="chkerr"}))}}function updateQuestionAnswer(a){ajaxObject().get("apps/misc.php?action=questions&inajax=1&update=yes",function(b){$(a).innerHTML=b})}var fixedLayerIndex=99900;
function displayFixedAdLayer(a,b,c,d){fixedLayerIndex++;var e=document.createElement("div");setTimeout(function(){try{document.body.insertBefore(e,null)}catch(a){}},100);e.style.position=phpcom.isIE6?"absolute":"fixed";e.style.zIndex=fixedLayerIndex;0==d?(e.style.bottom="0px",e.style.left="0px"):1==d?(e.style.bottom="0px",e.style.right="0px"):2==d?(e.style.top="120px",e.style.left="5px"):(e.style.top="120px",e.style.right="5px");b&&(e.style.width=b+"px");c&&(e.style.height=c+"px");e.innerHTML=a};
